# values.yaml for the Client Application

replicaCount: 1

image:
  repository: 370924438764.dkr.ecr.il-central-1.amazonaws.com/practice-project-client
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  hosts:
    - host: client.example.com # Replace with your desired hostname
      paths:
        - path: /
          pathType: Prefix

serverUrl: "http://staging-server-server-chart:3001"

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
