apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ if .Release }}{{ .Release.Name }}-client{{ else }}client-release-client{{ end }}
  labels:
    app.kubernetes.io/name: client-chart
    app.kubernetes.io/instance: {{ if .Release }}{{ .Release.Name }}{{ else }}client-release{{ end }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ if .Release }}{{ .Release.Name }}-client{{ else }}client-release-client{{ end }}
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
    {{- end }}