{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: staging-client-client
  labels:
    app: staging-client-client
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: staging-client-client
{{- end -}}